inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/SymbolArray:
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
